export const PATH = {
  admin: "/admin",
  postList: "/detail",
  productDetail: "/detail/:productId",
  login: "/login",
  register: "/register",
  registerSeller: "/registerSeller",
  authorize: "/authorize",
  order: "/authorize/order",
  cart: "/cart",
  review: "/review",
  payment: "/payment",
  dashboard: "/dashboard",
  manageProduct: "/dashboard/product",
  updateProduct: "/dashboard/product/update",
  createProduct: "/dashboard/product/create",
};
