export const PATH = {
  admin: "/admin",
  postList: "/detail",
  productDetail: "/detail/:postProductId",
  login: "/login",
  register: "/register",
  registerSeller: "/registerSeller",
  authorize: "/authorize",
  order: "/authorize/order",
  cart: "/cart",
  review: "/review/:orderId/:postProductId",
  payment: "/payment",
  dashboard: "/dashboard",
  manageProduct: "/dashboard/product",
  updateProduct: "/dashboard/product/update",
  createProduct: "/dashboard/product/create",
  transaction: "/dashboard/transaction",
  post: "/dashboard/post",

  loginStaff: "/loginStaff",
  admin: "/admin",
  manageStaffAcc: "/admin/staffManage",
  manageReportAcc: "/admin/reportAccManage",
  profileAdmin: "/admin/profile",
  profileAdminUpdate: "/admin/profile/update",

  moderator: "/moderator",
  managePost: "/moderator/post",
  manageReportPost: "/moderator/reportPost",
  profileModerator: "/moderator/profile",
  profileModeratorUpdate: "/moderator/profile/update",
};
